workspace = { members = ["example"] }
[package]
name = "graphql-hive-async-graphql-extension"
version = "0.0.1"
edition = "2021"
license = "MIT"

[features]
default = ["axum"]
axum = ["dep:axum-core", "dep:http"]

[dependencies]
async-graphql = { git = "https://github.com/XiNiHa/async-graphql.git", rev = "16785021140660f8d62b85c17fec51428f4eb523" }
graphql-hive-core = { path = "../core-rs" }
async-trait = "0.1"
derive_builder = "0.20"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
rand = "0.8"
axum-core = { version = "0.4", optional = true }
http = { version = "1", optional = true }

[dev-dependencies]
serde_json = "1"
