[package]
name = "async-graphql-extension-graphql-hive"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
async-graphql = "7"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde_json = "1"
