[package]
name = "async-graphql-extension-graphql-hive"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
async-graphql = { git = "https://github.com/XiNiHa/async-graphql.git", rev = "16785021140660f8d62b85c17fec51428f4eb523" }
graphql-hive-core = { path = "../core-rs" }
async-trait = "0.1"
derive_builder = "0.20"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
rand = "0.8"

[dev-dependencies]
serde_json = "1"
