import { AuditLogModel } from './providers/audit-logs-manager';

export type AuditLogMapper = AuditLogModel;
export type UserInvitedAuditLogMapper = AuditLogModel;
export type UserJoinedAuditLogMapper = AuditLogModel;
export type UserRemovedAuditLogMapper = AuditLogModel;
export type OrganizationSettingsUpdatedAuditLogMapper = AuditLogModel;
export type OrganizationTransferredAuditLogMapper = AuditLogModel;
export type OrganizationTransferredRequestAuditLogMapper = AuditLogModel;
export type ProjectCreatedAuditLogMapper = AuditLogModel;
export type ProjectSettingsUpdatedAuditLogMapper = AuditLogModel;
export type ProjectDeletedAuditLogMapper = AuditLogModel;
export type TargetCreatedAuditLogMapper = AuditLogModel;
export type TargetSettingsUpdatedAuditLogMapper = AuditLogModel;
export type TargetDeletedAuditLogMapper = AuditLogModel;
export type SchemaPolicySettingsUpdatedAuditLogMapper = AuditLogModel;
export type SchemaCheckedAuditLogMapper = AuditLogModel;
export type SchemaPublishAuditLogMapper = AuditLogModel;
export type SchemaDeletedAuditLogMapper = AuditLogModel;
export type RoleCreatedAuditLogMapper = AuditLogModel;
export type RoleAssignedAuditLogMapper = AuditLogModel;
export type RoleDeletedAuditLogMapper = AuditLogModel;
export type RoleUpdatedAuditLogMapper = AuditLogModel;
