{
 "title": "CDN Usage",
 "tags": [
  "hive",
  "cdn"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "query": "vertamedia-clickhouse-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests by status code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    blob1 AS statusCode,\n    COUNT() as total\nFROM hive_ha_cdn_response_ENV_NAME\n\nWHERE $timeFilter\n\nGROUP BY\n    statusCode,\n    t\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 20) * 20) * 1000 AS t,\n    blob1 AS statusCode,\n    COUNT() as total\nFROM hive_ha_cdn_response_ENV_NAME\n\nWHERE timestamp >= toDateTime(1694666628) AND timestamp <= toDateTime(1694688228)\n\nGROUP BY\n    statusCode,\n    t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Response by status code",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    blob1 AS statusCode,\n    COUNT() as total\nFROM hive_ha_cdn_response_ENV_NAME\n\nWHERE $timeFilter\n\nGROUP BY\n    statusCode,\n    t\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 20) * 20) * 1000 AS t,\n    blob1 AS statusCode,\n    COUNT() as total\nFROM hive_ha_cdn_response_ENV_NAME\n\nWHERE timestamp >= toDateTime(1694666678) AND timestamp <= toDateTime(1694688278)\n\nGROUP BY\n    statusCode,\n    t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Requests by path and status code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    blob1 AS statusCode,\n    blob2 as requestPath,\n    COUNT() as total\nFROM hive_ha_cdn_response_ENV_NAME\n\nWHERE $timeFilter\n\nGROUP BY\n    statusCode,\n    requestPath,\n    t\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 AS t,\n    blob1 AS statusCode,\n    blob2 as requestPath,\n    COUNT() as total\nFROM hive_ha_cdn_response_ENV_NAME\n\nWHERE timestamp >= toDateTime(1699350434) AND timestamp <= toDateTime(1699350734)\n\nGROUP BY\n    statusCode,\n    requestPath,\n    t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "R2 calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 14 },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    blob1 AS action,\n    blob2 AS statusCode,\n    COUNT() as total\nFROM hive_ha_cdn_r2_ENV_NAME\n\nWHERE $timeFilter\n\nGROUP BY\n    action,\n    statusCode,\n    t\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 20) * 20) * 1000 AS t,\n    blob1 AS action,\n    blob2 AS statusCode,\n    COUNT() as total\nFROM hive_ha_cdn_r2_ENV_NAME\n\nWHERE timestamp >= toDateTime(1694666810) AND timestamp <= toDateTime(1694688410)\n\nGROUP BY\n    action,\n    statusCode,\n    t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "R2 calls",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    blob1 AS action,\n    blob2 AS statusCode,\n    COUNT() as total\nFROM hive_ha_cdn_r2_ENV_NAME\n\nWHERE $timeFilter\n\nGROUP BY\n    action,\n    statusCode,\n    t\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 20) * 20) * 1000 AS t,\n    blob1 AS action,\n    blob2 AS statusCode,\n    COUNT() as total\nFROM hive_ha_cdn_r2_ENV_NAME\n\nWHERE timestamp >= toDateTime(1694666815) AND timestamp <= toDateTime(1694688415)\n\nGROUP BY\n    action,\n    statusCode,\n    t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "R2 calls (p95 latency)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    blob1 AS action,\n    quantileWeighted(0.95, double1, _sample_interval) as p95\nFROM hive_ha_cdn_r2_ENV_NAME\n\nWHERE $timeFilter\n\nGROUP BY\n    action,\n    t\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 20) * 20) * 1000 AS t,\n    blob1 AS action,\n    quantileWeighted(0.95, double1, _sample_interval) as p95\nFROM hive_ha_cdn_r2_ENV_NAME\n\nWHERE timestamp >= toDateTime(1724821505) AND timestamp <= toDateTime(1724843105)\n\nGROUP BY\n    action,\n    t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Features",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 21 },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    blob2 AS feature,\n    COUNT() as total\nFROM hive_ha_cdn_usage_ENV_NAME\n\nWHERE $timeFilter\n\nGROUP BY\n    feature,\n    t\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 2) * 2) * 1000 AS t,\n    blob2 AS feature,\n    COUNT() as total\nFROM hive_ha_cdn_usage_ENV_NAME\n\nWHERE timestamp >= toDateTime(1671448241) AND timestamp <= toDateTime(1671451841)\n\nGROUP BY\n    feature,\n    t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Features",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n  $timeSeries AS t,\n\tblob2 AS feature,\n\tCOUNT() as total\nFROM hive_ha_cdn_usage_ENV_NAME\nWHERE $timeFilter\nGROUP BY feature, t\nORDER BY t",
     "rawQuery": "SELECT \n  (intDiv(toUInt32(timestamp), 1) * 1) * 1000 AS t,\n\tblob2 AS feature,\n\tCOUNT() as total\nFROM hive_ha_cdn_usage_ENV_NAME\nWHERE timestamp >= toDateTime(1671444869) AND timestamp <= toDateTime(1671445769)\nGROUP BY feature, t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 28 },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n  $timeSeries AS t,\n  blob1 AS cdnVersion,\n\tCOUNT() as total\nFROM hive_ha_cdn_usage_ENV_NAME\nWHERE $timeFilter\nGROUP BY cdnVersion, t\nORDER BY t",
     "rawQuery": "SELECT \n  (intDiv(toUInt32(timestamp), 20) * 20) * 1000 AS t,\n  blob1 AS cdnVersion,\n\tCOUNT() as total\nFROM hive_ha_cdn_usage_ENV_NAME\nWHERE timestamp >= toDateTime(1671424022) AND timestamp <= toDateTime(1671445622)\nGROUP BY cdnVersion, t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n  $timeSeries AS t,\n  blob1 AS cdnVersion,\n\tCOUNT() as total\nFROM hive_ha_cdn_usage_ENV_NAME\nWHERE $timeFilter\nGROUP BY cdnVersion, t\nORDER BY t",
     "rawQuery": "SELECT \n  (intDiv(toUInt32(timestamp), 1) * 1) * 1000 AS t,\n  blob1 AS cdnVersion,\n\tCOUNT() as total\nFROM hive_ha_cdn_usage_ENV_NAME\nWHERE timestamp >= toDateTime(1671444913) AND timestamp <= toDateTime(1671445813)\nGROUP BY cdnVersion, t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 34 },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    blob1,\n    blob2,\n    COUNT() as total\nFROM hive_ha_cdn_error_ENV_NAME\n\nWHERE $timeFilter\n\nGROUP BY\n    t,\n    blob1,\n    blob2\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 AS t,\n    blob1,\n    blob2,\n    COUNT() as total\nFROM hive_ha_cdn_error_ENV_NAME\n\nWHERE timestamp >= toDateTime(1674578665) AND timestamp <= toDateTime(1674579565)\n\nGROUP BY\n    t,\n    blob1,\n    blob2\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n  $timeSeries AS t,\n  blob1,\n  blob2,\n\tCOUNT() as total\nFROM hive_ha_cdn_error_ENV_NAME\nWHERE $timeFilter\nGROUP BY blob1, blob2, t\nORDER BY t",
     "rawQuery": "SELECT \n  (intDiv(toUInt32(timestamp), 30) * 30) * 1000 AS t,\n  blob1,\n  blob2,\n\tCOUNT() as total\nFROM hive_ha_cdn_error_ENV_NAME\nWHERE timestamp >= toDateTime(1672691916) AND timestamp <= toDateTime(1672735116)\nGROUP BY blob1, blob2, t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Errors in total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n  $timeSeries AS t,\n\tCOUNT() as total\nFROM hive_ha_cdn_error_ENV_NAME\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT \n  (intDiv(toUInt32(timestamp), 15) * 15) * 1000 AS t,\n\tCOUNT() as total\nFROM hive_ha_cdn_error_ENV_NAME\nWHERE timestamp >= toDateTime(1674558093) AND timestamp <= toDateTime(1674579693)\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Key validation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 40 },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    blob1 AS action,\n    blob2 AS value,\n    COUNT() as total\nFROM hive_ha_cdn_key_validation_ENV_NAME\n\nWHERE $timeFilter\n\nGROUP BY\n    action,\n    value,\n    t\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 2) * 2) * 1000 AS t,\n    blob1 AS action,\n    blob2 AS value,\n    COUNT() as total\nFROM hive_ha_cdn_key_validation_ENV_NAME\n\nWHERE timestamp >= toDateTime(1674646874) AND timestamp <= toDateTime(1674650474)\n\nGROUP BY\n    action,\n    value,\n    t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Key validation",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries AS t,\n    blob1 AS action,\n    blob2 AS value,\n    COUNT() as total\nFROM hive_ha_cdn_key_validation_ENV_NAME\n\nWHERE $timeFilter\n\nGROUP BY\n    action,\n    value,\n    t\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 2) * 2) * 1000 AS t,\n    blob1 AS action,\n    blob2 AS value,\n    COUNT() as total\nFROM hive_ha_cdn_key_validation_ENV_NAME\n\nWHERE timestamp >= toDateTime(1674646880) AND timestamp <= toDateTime(1674650480)\n\nGROUP BY\n    action,\n    value,\n    t\nORDER BY t",
     "round": "0s"
    }
   ]
  }
 ]
}