{
 "title": "Container Logs",
 "tags": [
  "kubernetes",
  "logs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service:",
    "query": {}
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Errors over time (all services)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(container_name) (rate({env=\"prod\"} |= `\"level\":50` [$__interval]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "service" },
  {
   "title": "Recent Log Errors/Warnings of $service",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{container_name=\"$service\"} | json | regexp `(?P<requestId>[a-f0-9-]{36})`| line_format \"{{ .msg }}\" | __error__ != `JSONParserErr` | level > 30"
    }
   ]
  },
  {
   "title": "Service Logs of $service",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{container_name=\"$service\"} | json | __error__ != `JSONParserErr` | regexp `(?P<requestId>[a-f0-9-]{36})` | line_format `{{ .msg }}`"
    }
   ]
  }
 ]
}