{
 "title": "Hive Tokens Metrics",
 "tags": [
  "hive",
  "tokens"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(tokens_http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET / throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(tokens_http_requests_total[$__range]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(tokens_http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(tokens_cache_hits_total[$__rate_interval]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(rate(tokens_cache_misses_total[$__rate_interval]))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "stat",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tokens_cache_hits_total[$__rate_interval]))/ (sum(rate(tokens_cache_hits_total[$__rate_interval])) + sum(rate(tokens_cache_misses_total[$__rate_interval])))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Cache fill ups",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(tokens_cache_fillups_total[$__rate_interval]))",
     "legendFormat": "Fill ups"
    }
   ]
  },
  {
   "title": "Cache invalidations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(tokens_cache_invalidations_total[$__rate_interval]))",
     "legendFormat": "Invalidations"
    }
   ]
  }
 ]
}