{
 "title": "Schema Service metrics",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "\"Compose and Validate\" calls by project type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(type) (rate(schema_compose_and_validate_total[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "\"Compose and Validate\" calls by project type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(type) (rate(schema_compose_and_validate_total[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Successful composition requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(cache) (rate(schema_external_composition_total{type=\"success\"}[$__rate_interval]))",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Successful composition requests",
   "type": "piechart",
   "description": "Events where Hive managed to get a composition result",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(cache) (rate(schema_external_composition_total{type=\"success\"}[$__rate_interval]))",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Failed composition requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(cache) (rate(schema_external_composition_total{type=\"failure\"}[$__rate_interval]))",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Failed composition requests",
   "type": "piechart",
   "description": "Failed to get a composition result due to an exception or network issue.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(cache) (rate(schema_external_composition_total{type=\"failure\"}[$__rate_interval]))",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(cache) (rate(schema_external_composition_total{type=\"timeout\"}[$__rate_interval]))",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(cache) (rate(schema_external_composition_total{type=\"timeout\"}[$__rate_interval]))",
     "legendFormat": "{{cache}}"
    }
   ]
  }
 ]
}