[package]
name = "graphql-hive-core"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
thiserror = "1"
# Until they release https://github.com/graphql-rust/graphql-parser/commit/0d93ac9310c2894a029d0eb912c3463875a535f9
graphql-parser = { git = "https://github.com/graphql-rust/graphql-parser.git", rev = "8d76425d83c40670570cc325f57c730262f07456" }
graphql-tools = { git = "https://github.com/dotansimha/graphql-tools-rs.git", rev = "59d083108c63fb24a525f987ac4299d108c6e2d1" } # branch = "kamil-minifier-without-fork"
serde = "1"
tokio = { version = "1", features = ["time", "sync"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
lru = "0.12"
sha2 = "0.10"
md5 = "0.7"
